### ISSUE TITLE
v1.2.0 崩溃

### ISSUE THREAD

**Issue by ZhangYaoan** [cledwynl/mbga#59]
LineageOS 21, Android 14

Bilibili 3.19.2

Crash report:
```
FATAL EXCEPTION: main
Process: top.trangle.mbga, PID: 18341
java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
	at android.app.ContextImpl.checkMode(ContextImpl.java:3567)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:598)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:588)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:223)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:223)
	at top.trangle.mbga.views.SettingsActivity$a.N(Unknown Source:34)
	at a0.s.v(Unknown Source:67)
	at androidx.fragment.app.L.e(Unknown Source:65)
	at androidx.fragment.app.L.k(Unknown Source:153)
	at androidx.fragment.app.G.z(Unknown Source:1031)
	at androidx.fragment.app.G.Q(Unknown Source:81)
	at androidx.fragment.app.G.y(Unknown Source:77)
	at androidx.fragment.app.G.t(Unknown Source:66)
	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:33)
	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1705)
	at android.app.Activity.performStart(Activity.java:9003)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4018)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by cledwynl** [comment]
lsp版本是多少

**Comment by ZhangYaoan** [comment]
> lsp版本是多少

```
API 版本
100

Xposed API 调用保护
已启用

Dex 优化器包装
支持

框架版本
1.9.3_mod (7244)

管理器包名
com.android.shell

系统版本
14 (API 34)

设备
Xiaomi Redmi 22041216C 

系统架构
arm64-v8a
```

**Comment by seraph758** [comment]
我用lsposed mod就崩溃，后来换了一个lsposed 就正常了。楼主也可以试试

**Comment by ZhangYaoan** [comment]
我测试了 [JingMatrix/LSPosed](https://github.com/JingMatrix/LSPosed) 1.10.1 和 [mywalkb/LSPosed_mod](https://github.com/mywalkb/LSPosed_mod) 都存在这个问题，而原版 LSPosed 在我的设备上不能正常工作

**Comment by AliasQli** [comment]
> 后来换了一个lsposed 就正常了。

因为停更，很多设备上原版lsposed已经不能在新版magisk下工作了。

**Comment by FunctionXJB** [comment]
我的也是安卓15，原版1.9.2 lsp不能用，用mod版就会闪退

**Comment by nzmxd** [comment]
在Android15下，我测试了一下，使用原版lsposed勾选后模块可以正常使用MODE_WORLD_READABLE权限并打开应用，但是lsposed_mod勾选模块后无法使用MODE_WORLD_READABLE权限应用会闪退，应该是LSPosed hooks 的ContextImpl.checkMode(int)逻辑失效了

**Comment by ProgrammedSoul** [comment]
[JingMatrix/LSPosed](https://github.com/JingMatrix/LSPosed)1.10.2版本在一些Android 15环境里可用，测试机型为Mogo G Power 2025。Root方法为APatch 0.12.0(11107)，Zygisk实现方法为Zygisk Next 1.2.9.1。
